version: 2
sources:
  - name: external_source
    meta:
      external_location: "s3://datafy-dp-samples-ympfsg/TPCDS-TEST-100G/{name}/*.parquet"
    tables:
      - name: call_center
      - name: catalog_page
      - name: catalog_returns
      - name: catalog_sales
      - name: customer_address
      - name: customer_demographics
      - name: customer
      - name: date_dim
      - name: household_demographics
      - name: income_band
      - name: inventory
      - name: item
      - name: promotion
      - name: promotion_demographics
      - name: reason
      - name: ship_mode
      - name: store_returns
      - name: store_sales
      - name: store
      - name: time_dim
      - name: web_page
      - name: web_returns
      - name: web_sales
      - name: web_site
      - name: warehouse
